spring: 
  datasource:
    url: jdbc:mysql://exqress-rds.ctxktr2nwban.ap-northeast-2.rds.amazonaws.com:3306/exqressdb
    username: admin
    password: qwer1234
    driver-class-name: com.mysql.cj.jdbc.Driver

token:
  expiration_time: 864000
  secret: ndjdsnfajkgbdskwj31jgfduhoe28

