spring: 
  datasource:
    url: jdbc:h2:tcp://localhost/~/user-service
    username: sa
    password: '{cipher}AQCClbFB0HBOcWGxDuO1SwJh/3DjdkXMtwuPsiHU/KzQVSPw7ZqMjRmuSdG00e55xhpYpFlyQ1nAy/psc65N2QHfSaCZE12w2+l30M90dWUmt8s4rgw70t/4XK4QhuJ95aRPoSI/qDTGXNP4j3Pf4VgL9nXn8Nt8URmCzXkPEThxm2lzhJqQwsIe5NoQgKctq6bYstWY6uOt1w+DlPd2p2nKTCI3mmeubdVONuq9K99NFs8oWsoOMAVjVNEbLyVCk6RKsGbj4wlbpdcf+c9m7Cw5nvon8Q6by1d2yhiaJJi36s493hDAlKa558eQ0vkIIVr012pwoFqcGbU/t/7ekc8CZmEr2VeXIEII8wuetL6XuLU6nKwMXJDHdQiAY9Pjuao='
    driver-class-name: org.h2.Driver

token:
  expiration_time: 864000
  secret: '{cipher}AQBCA1WzHsQKK1663pLmEeeh/lABZShpaZUSxzuRLxFsZoEiSQ+WnZbfXqwHiq9QWwcYUI1o7LzcB+lxXSd4+1E435MoIgdzt9T1l67VEBN/EBqg1GK5BpkNQW8pIpqZfIVpqDiZSBfqBorNAidd8GL5ZGA0uGbgzxJwBjiDMd0ynYJDIfxyY/tDChksaYqPH/O6MhPNXM75qqPERv2wfs+F2BgEkZEqJO+adrwAVdOgKI0+QI5z+mKVANn/F5Fva7pc19vm8sWZb9tQIbioMOFGD6GyIK4wv6p1RygsD+PIqGIs+rRZUIKTqd00Z4q1vu673Ha3nGSIiRPq3cN90ivXsZdVEsoRDIr52dB9yOvOLU23s7380XZwDLlPVTBqm/VaoLiRCZ771P5Zm75frrd9'

order_service:
  url: http://127.0.0.1:8000/delivery-service/%s/items