spring: 
  datasource:
    url: jdbc:h2:tcp://localhost/~/user-service
    username: sa
    password: 1234
    driver-class-name: org.h2.Driver

token:
  expiration_time: 864000
  secret: jkdaknfajkdjkdlkad

order_service:
  url: http://DELIVERY-SERVICE/delivery-service/%s/items