spring: 
  datasource:
    url: jdbc:h2:tcp://localhost/~/user-service
    username: sa
    password: 1234
    driver-class-name: org.h2.Driver

token:
  expiration_time: 864000
  secret: '{cipher}AQBCA1WzHsQKK1663pLmEeeh/lABZShpaZUSxzuRLxFsZoEiSQ+WnZbfXqwHiq9QWwcYUI1o7LzcB+lxXSd4+1E435MoIgdzt9T1l67VEBN/EBqg1GK5BpkNQW8pIpqZfIVpqDiZSBfqBorNAidd8GL5ZGA0uGbgzxJwBjiDMd0ynYJDIfxyY/tDChksaYqPH/O6MhPNXM75qqPERv2wfs+F2BgEkZEqJO+adrwAVdOgKI0+QI5z+mKVANn/F5Fva7pc19vm8sWZb9tQIbioMOFGD6GyIK4wv6p1RygsD+PIqGIs+rRZUIKTqd00Z4q1vu673Ha3nGSIiRPq3cN90ivXsZdVEsoRDIr52dB9yOvOLU23s7380XZwDLlPVTBqm/VaoLiRCZ771P5Zm75frrd9'

order_service:
  url: http://DELIVERY-SERVICE/delivery-service/%s/items